---
on:
  - push

jobs:
  Terraform_Init:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9